"""Charging cards, transaction identity, meter samples and reconciliation."""

from alembic import op

revision = "d830a62f194b"
down_revision = "a721093e4f62"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        "CREATE TABLE charging_cards (\n\tid UUID NOT NULL, \n\ttag_hash VARCHAR(64) NOT NULL, \n\ttag_tail VARCHAR(4) NOT NULL, \n\tdriver_id UUID NOT NULL, \n\tissuer_id UUID NOT NULL, \n\tstatus VARCHAR(20) DEFAULT 'active' NOT NULL, \n\texpires_at TIMESTAMP WITH TIME ZONE, \n\tcreated_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tUNIQUE (tag_hash), \n\tFOREIGN KEY(driver_id) REFERENCES users (id) ON DELETE RESTRICT, \n\tFOREIGN KEY(issuer_id) REFERENCES users (id) ON DELETE RESTRICT\n)"
    )
    op.execute("CREATE INDEX ix_charging_cards_issuer_id ON charging_cards (issuer_id)")
    op.execute(
        "CREATE TABLE charging_authorization_attempts (\n\tid UUID NOT NULL, \n\tcharge_point_id UUID NOT NULL, \n\ttag_tail VARCHAR(4) NOT NULL, \n\tresult VARCHAR(20) NOT NULL, \n\treceived_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(charge_point_id) REFERENCES charge_points (id) ON DELETE CASCADE\n)"
    )
    op.execute(
        "CREATE INDEX ix_charging_authorization_attempts_charge_point_id ON charging_authorization_attempts (charge_point_id)"
    )
    op.execute(
        "CREATE TABLE charging_sessions (\n\tid INTEGER GENERATED BY DEFAULT AS IDENTITY (MAXVALUE 2147483647), \n\tcharge_point_id UUID NOT NULL, \n\tconnector_id UUID NOT NULL, \n\tdriver_id UUID, \n\ttag_tail VARCHAR(4) NOT NULL, \n\tauthorization_status VARCHAR(20) NOT NULL, \n\tstarted_at TIMESTAMP WITH TIME ZONE NOT NULL, \n\tended_at TIMESTAMP WITH TIME ZONE, \n\tmeter_start_wh NUMERIC(24, 6) NOT NULL, \n\tmeter_stop_wh NUMERIC(24, 6), \n\tenergy_kwh NUMERIC(24, 6), \n\tstop_reason VARCHAR(50), \n\treview_reasons JSONB DEFAULT '[]' NOT NULL, \n\treceived_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(charge_point_id) REFERENCES charge_points (id) ON DELETE CASCADE, \n\tFOREIGN KEY(connector_id) REFERENCES connectors (id) ON DELETE RESTRICT, \n\tFOREIGN KEY(driver_id) REFERENCES users (id) ON DELETE RESTRICT\n)"
    )
    op.execute(
        "CREATE INDEX ix_charging_sessions_charge_point_id ON charging_sessions (charge_point_id)"
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_charging_sessions_open_connector ON charging_sessions (connector_id) WHERE ended_at IS NULL"
    )
    op.execute(
        "CREATE TABLE charging_meter_samples (\n\tid INTEGER GENERATED BY DEFAULT AS IDENTITY, \n\tsession_id INTEGER NOT NULL, \n\ttimestamp TIMESTAMP WITH TIME ZONE NOT NULL, \n\tmeasurand VARCHAR(50) NOT NULL, \n\tphase VARCHAR(10) DEFAULT '' NOT NULL, \n\tlocation VARCHAR(10) DEFAULT 'Outlet' NOT NULL, \n\tvalue NUMERIC(24, 6) NOT NULL, \n\tunit VARCHAR(10) NOT NULL, \n\tPRIMARY KEY (id), \n\tCONSTRAINT uq_charging_meter_sample UNIQUE (session_id, measurand, phase, location, timestamp), \n\tFOREIGN KEY(session_id) REFERENCES charging_sessions (id) ON DELETE CASCADE\n)"
    )
    op.execute(
        "CREATE INDEX ix_charging_meter_session_time ON charging_meter_samples (session_id, timestamp)"
    )
    op.execute(
        "CREATE TABLE charging_pending_messages (\n\tid UUID NOT NULL, \n\tcharge_point_id UUID NOT NULL, \n\taction VARCHAR(30) NOT NULL, \n\tmessage_id VARCHAR(36) NOT NULL, \n\treason VARCHAR(100) NOT NULL, \n\tpayload JSONB NOT NULL, \n\treceived_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL, \n\tPRIMARY KEY (id), \n\tFOREIGN KEY(charge_point_id) REFERENCES charge_points (id) ON DELETE CASCADE\n)"
    )
    op.execute(
        "CREATE INDEX ix_charging_pending_messages_charge_point_id ON charging_pending_messages (charge_point_id)"
    )


def downgrade() -> None:
    op.drop_table("charging_pending_messages")
    op.drop_table("charging_meter_samples")
    op.drop_table("charging_sessions")
    op.drop_table("charging_authorization_attempts")
    op.drop_table("charging_cards")
